### PR TITLE
use version number instead of release in .travis.yml

### PR DESCRIPTION
**Pull request by tkelman**
release will change over time, but your REQUIRE file says this package supports julia 0.5 so it should continue to be tested

### CODE REVIEW

**Comment by djsegal** [comment]
This needs to get changed in `init` also, b/c this line gets auto-added to new packages

**Comment by tkelman** [comment]
Where? I don't see any other instance of "release" in the code here

**Comment by djsegal** [comment]
Oh, I thought you were talking about:

https://github.com/djsegal/Julz.jl/blob/master/src/functions/commands/init.jl#L143-L144

Thanks for catching that!

**Comment by djsegal** [comment]
Would an alternative be to just change the line in `REQUIRE`

from:

```
julia 0.5
```

to:

```
julia 0.5+
```

// add a `+` sign

**Comment by tkelman** [comment]
that would make the latest versions of the package no longer installable on 0.5.0, I don't think that's what you want?

the problem is just that REQUIRE should match what gets tested on travis, and when 0.6.0 comes out and release changes meaning, that would no longer be the case. you should update REQUIRE and .travis.yml in concert when you choose to, not have one of them change out from underneath you, outside of your control

**Comment by djsegal** [comment]
fixed by: https://github.com/djsegal/Julz.jl/commit/7a98c8eb0d43973e7b21a3a7973e793770e5f142

**Pull request closed without merging**
